label day2:
    scene bedroom with fade
    "(Is that knocking?! Who could be brazen enough to wake me up so early?!)"
    p "Niir! I am in no mood for your games! Begone!"
    c "Please, Princess, it is I, Cyril, and I only wanted to-"
    p "Moronious?! This had better be important!"
    c "Good.  Good.  I'm glad that you opened up."
    c "I don't want you to think that I'm - well, dissapproving."
    c "But some information has come to my attention."
    c "You were {b}banished{/b} Princess!"
    p "I am well aware of that.  So what are you bothering me for?"
    c "It's just you were {b}banished{/b} Princess!"
    p "If you're going to waste my time like a stuttering fool Moronious, I suggest you begone!"
    c "Well, it wouldn't be the first time that you've commanded me to begone."
    c "Anyway, please tell me this is a mistake!  It must be a mistake!"
    c "I'm sure that the kingdom is just overreacting.  Playing a Niir-like joke perhaps?"
    c "There is no way they would actually b-b-banish you!"
    p "Oh, they did banish me.  And that's why I'm here, to get justice."
    p "And you will be part of those plans Cyril."
    c "Erm-ahem!  Yes.  I don't think that is a good idea- it is already dangerous enough to have a disgraced Princess-"
    p "You don't {b}want{/b} me here?"
    p "(Who does he think he is?  I'm not the one at fault here!  I'd like to {b}see{/b} him try to kick me out!)"
    c "No! I didn't say that."
    c "I'm just {i}concerned{/i} Princess."
    c "If you have serious allegations before you then ah-"
    p "You're ashamed of me being in your presence, then?"
    c "No!  I love you being in my presence."
    c "{i}I do{/i}.  It's just..."
    c "I'm afraid for you and the errr... connotations that are attached to that."
    p "I can handle myself Moronious."
    p "And when I put things right you will see that for yourself."
    c "As long as I'm not seen as {i}aiding and abetting{/i}."
    p "If you are not willing to make sacrifices for your future Queen then what good are you?"
    c "I am, I am.  Forgive me your majesty."
    p "I forgive you, you foolish mage.  Just don't doubt me again."
    
    #TODO: Have a conversation with Niir and Balrung somehow?!